### ISSUE TITLE
大佬，之前知乎上发过的还搬过来吗？

### ISSUE THREAD

**Issue by thePOET8** [Anticorianderist/de-vegetable#1]
很庆幸之前在知乎上看过大佬的文章，当时还截图收藏了不少，今天再去看时找不到收藏的了，拿之前的截图里的文字去搜也没搜到，才发现是退乎了（之前看大佬动态就感觉是要退了）。
        就是觉得之前知乎上发的就这样消逝了感到可惜，还请问大佬还搬过来吗。感谢感谢

**Comment by Anticorianderist** [comment]
> ```
>    很庆幸之前在知乎上看过大佬的文章，当时还截图收藏了不少，今天再去看时找不到收藏的了，拿之前的截图里的文字去搜也没搜到，才发现是退乎了（之前看大佬动态就感觉是要退了）。
>     就是觉得之前知乎上发的就这样消逝了感到可惜，还请问大佬还搬过来吗。感谢感谢
> ```

我把所有文章搬过来了（要么在blog，要么在love），但知乎回答没有备份。

**Comment by thePOET8** [comment]
好的，感谢感谢，您是我的带路人
