### ISSUE TITLE
必然与偶然

### ISSUE THREAD

**Issue by sakura241225** [Anticorianderist/de-vegetable#11]
学长，请问是否可以这样理解？

对于一个人 其恋爱标准无论如何，都一定会结婚（假设这人未来结婚）在这个必然下，他专注于美貌，或者他考验对方是否讲道理，没有不良嗜好。
在结婚的必然下，他不同的选择得到了不同的偶然性。

上述结婚是必然的，但是他的婚姻质量如何是偶然的。

而在大学，以后工作是必然的，而在大学选择学什么是偶然的。假如，一个大一化工学生看到学长文章，选择计算机，但还是未来还是要工作的。
工作是必然的，但是生活的质量又是会发生巨大改变的。

对于大环境  在大环境是一定会裁员情况下，由于曾经学了大数据被公司需要而没有被裁员，这是人的偶然性。
对个人，对社会，必然性是你一定会做，偶然性是过得可能好或者不好，或者说是过得质量的变化。

例如学长的例子，我寒假一定回家。如果我只是打打王者，就过得比较无聊，没啥意思。而如果我之前刷知乎看到一个推荐书单的回答，而准备去看书，过得稍微有点意义。

不知理解对吗？感觉有点选错对象了。

**Comment by Anticorianderist** [comment]
明天晚上回复。

**Comment by Anticorianderist** [comment]
> 学长，请问是否可以这样理解？
> 
> 对于一个人 其恋爱标准无论如何，都一定会结婚（假设这人未来结婚）在这个必然下，他专注于美貌，或者他考验对方是否讲道理，没有不良嗜好。 在结婚的必然下，他不同的选择得到了不同的偶然性。
> 
> 上述结婚是必然的，但是他的婚姻质量如何是偶然的。
> 
> 而在大学，以后工作是必然的，而在大学选择学什么是偶然的。假如，一个大一化工学生看到学长文章，选择计算机，但还是未来还是要工作的。 工作是必然的，但是生活的质量又是会发生巨大改变的。
> 
> 对于大环境 在大环境是一定会裁员情况下，由于曾经学了大数据被公司需要而没有被裁员，这是人的偶然性。 对个人，对社会，必然性是你一定会做，偶然性是过得可能好或者不好，或者说是过得质量的变化。
> 
> 例如学长的例子，我寒假一定回家。如果我只是打打王者，就过得比较无聊，没啥意思。而如果我之前刷知乎看到一个推荐书单的回答，而准备去看书，过得稍微有点意义。
> 
> 不知理解对吗？感觉有点选错对象了。

这个理解是对的，但你可以再结合数学篇正定欠定超定的理念继续深入一点。必然和偶然是一个哲学范畴，你怎么想都可以。如果你要让它产生更具体的作用，我可以继续展开你的理解。以找工作为例：

语境1：在当前的语境下，工作是必然的，因为需要靠工作养活自己。工作A和工作B是偶然的。可能你的高考志愿就是三个不同的专业，但在不知道每个志愿投档线的情况下，工作A和工作B也许对应一分之差。可是，工作A真的完全是偶然的吗？

语境2：假如你是一个比较卷的人，无论你选的是什么专业，你都试图转行到金融计算机师医公。那么，原来的偶然性从工作ABCDEFGHIJKLMN压缩到了工作ABC。我们可以把它再次套入必然偶然的语境：一开始进入高薪的ABCD和低薪的HIJK是偶然的，但如果你是一个卷王，那你进入高薪的ABCD是必然的。

语境1和语境2的差异是什么？你通过自己的特征（卷），增加了必然（从工作到高薪的工作），减少了偶然。

同理，矛盾论的对立统一其实可以把必然和偶然讲得非常丰富：你可以认为必然是一种宏观的大趋势，偶然是一种微观的小细节。但是，这种宏观和微观取决于你的视角，如果你的粒度特别特别细，那么必然会越来越多。你对人生的掌控力也会越来越强。如果再结合数学加以解释，偶然（随机）的本质是信息的欠定（比如，如果没意识到自己很卷，那么高薪就是一种偶然而不是必然）。

类似地，你可以往宏观了想“工作是必然的吗”，其实不工作也可以当流浪汉或乞丐。这个视角又可以让人生所处的系统变得更加宏大，使得原先的必然（一定工作）成为偶然（可能当流浪汉）。这个视角的本质是介入了新的观察和理解。“一定工作”是一种常见的社会规训，但你可能因为读了《月亮和六便士》或《生活在树上》就多了一层复杂性。

所以，在对立统一的立场下，必然和偶然是收放自如的。如果你可以将这个过程结合矛盾论本身（哲学）和概率论（数学），这就是自我解析、认识世界以及掌控人生的利器。

**Comment by sakura241225** [comment]
根据学长的描述，其实所谓必然和偶然是信息差的问题。

宏观的必然是相对的 其实是因为宏观需要的信息比较少，微观判断的信息更多一点。二战一定会发生只需要一部分信息就可以判断。而二战导火索对大部分人来说就是不可预测的。因为只有知道很多很多信息才可以判断。

必然和偶然是相对的 暑假之前一直回家的我，发现了一份非常好的暑假工，就留下打工。而之前一直回家的必然行打破了。修改为除非好工作，一般情况下回家的更加精确的必然性。

那么说，其实世间是必然的，只是人类观察的能力导致了偶然和必然的情况。随着人观察能力的不同，必然和偶然也是不断精确的。有种和认识论很相似的感觉了😂

感觉自己有点理解可能有些片面，混乱了，或者说是着急了，先得把之前的哲学概念理解并且记忆，才能刚好的运用到社会中

**Comment by sakura241225** [comment]
感觉还可以把必然和偶然和归因联系在一起。

可能这些概念理解的不够深入，有些混乱，应该在多多看书，然后把概念记住。

谢谢学长的解答！
(ˊ˘ˋ*)♡
