### ISSUE TITLE
"typo"

### ISSUE THREAD

**Issue by SchweitzerGAO** [Anticorianderist/de-vegetable#13]
[此文](https://github.com/Anticorianderist/de-vegetable/blob/main/1-src/2-self-educations/2-math/3-life-model.md)第0x03部分\exist 无法正常渲染为latex, 应改为\exists

**Comment by Anticorianderist** [comment]
> [此文](https://github.com/Anticorianderist/de-vegetable/blob/main/1-src/2-self-educations/2-math/3-life-model.md)第0x03部分\exist 无法正常渲染为latex, 应改为\exists

Fixed.
