### ISSUE TITLE
如何感受生活中的乐趣？

### ISSUE THREAD

**Issue by sakura241225** [Anticorianderist/de-vegetable#15]
学长，好久不见！有个问题一直想请教。希望能解答一下。

有句话说生活处处有美，只不过是缺乏发现美的眼睛。弗兰克有本书讲他在集中营，在这种极端的环境下，他思考关于人生的意义，以此度过了这阶段，使他更加清楚的认识自己。

而我面临的生活，总是有种压抑的感觉。尝试过很多的事情，比如打游戏，看小说，看哲理书，还有出去逛等。除了运动之后的舒畅给我生活带来些许真实，基本无太大变化。

那些生活在很困难的生活的一些人，他们能苦中作乐，能够发现生活中的美。他们活的很是精彩，有斗志和生命力。他们没有失去童趣心。即使生活对他很是残酷。

而我去发现生活中的乐趣，却难以寻到。对于平淡琐事，可以说有些许感触，但大体上还是归于平淡。

既不是讨厌一些事物，而一种对大部分事情是一种很无所谓，无意义的态度。不知道是不是自己像是死亡诗社中的那些已算是行尸走肉的人。
高雅的艺术，不感兴趣。低俗的凡事，仍无乐趣。
不知是因为自己对事物的观察力不足，还是因为人际关系有不足。或者说是应该去尝试先苦后甜。中学时，如果一周没有接触手机，回家打游戏的话，刚开始是特别放松的。

不知是方法论的不足，还是心态的急躁。去阻碍发现生活中的美好。

**Comment by Anticorianderist** [comment]
晚上回复。

**Comment by sakura241225** [comment]
提问过于模糊，理不清自己的思路。感谢学长的回答。

仔细思考了一下。我自身的问题是多方面的，他们影响的我欣赏美的能力。
对于欣赏美来说。

在学校的睡眠质量差，经常使用电子设备，对求学的压力，以及所处的环境不同，即用手机看电影和在用电脑和在电影院所带来的感官是不同的。即使打游戏这种快感，在困倦的时候，依靠多巴胺打游戏越玩越痛苦。
对于积极来说，由于身体的不充分休息，导致自己精神上，是忽略身边的一些美，或者那些乐趣的事情。

当时好奇的一个点在于，像是活着的主人公经历了那么多苦难却仍然乐观活着。还能笑着谈自己的经历，给我一种很震撼的感觉。又或者wg时期关入牛棚的很多人，有的完全丧失了生的生机勃勃，像是行尸走肉。而有的人在经历的这些，仍然有斗志。
仔细想想，是他们对于一件事的理解可能不同。有些人视为人生的疤痕，能够去反思，疤痕的存在的因素等等，去结构他，而在意疤痕的人却很是痛苦。又或者说是史铁生，在他文字的生命力的体现。他在意出现他身上的苦难，但不沉浸于其中。而通过他所处的环境对自己进行思考。

总之，谢谢学长的回复。有很大的启发。
