### ISSUE TITLE
初等数学一节，引例中的教材页码需要更新

### ISSUE THREAD

**Issue by tuuzy** [Anticorianderist/de-vegetable#18]
2-self-education/2-math/2-elementary-math一节，引例中“[[国家中小学智慧教育平台](https://www.zxx.edu.cn/)]/教材/初中/数学/人教版/七年级上册/Page 54-Page 58”这句话中的页码需要更新，新版教材关于多项式的内容放在了Page 89-Page 92。

**Comment by Anticorianderist** [comment]
收到。谢谢你。
