### ISSUE TITLE
学术论文教程

### ISSUE THREAD

**Issue by langtaomv** [Anticorianderist/de-vegetable#2]
A佬有兴趣可以分享一些学术论文的写作经验，或者自己写一个教程^_^

**Comment by Anticorianderist** [comment]
> A佬有兴趣可以分享一些学术论文的写作经验，或者自己写一个教程^_^

如果2023-06-06的论文中了，肯定写！

😉😉😉

**Comment by langtaomv** [comment]
那就提前祝佬必中！！！
