### ISSUE TITLE
众生相中读人的标准

### ISSUE THREAD

**Issue by sakura241225** [Anticorianderist/de-vegetable#4]
更合理的读人标准，应该是对方的言行举止向你透露了多少有用信息。

ps:请教一下学长，这个意思是具体什么意思？

如果说从你观察到的对方的言行去判断这个人，还要观察是否对方透露。
1. 存在一个人特地向你透露片面的信息。比如渣男对女性的片面信息去，读人不就有偏差了。
2.人是多面的 你不能从一个人向你透露的言行彻底了解一个人。可能对普通人还能说的通。对我影响最深的就是白银杀人案的凶手了。

是否说说高手可以见微知著呢？

顺便感谢之前学长的答复₍˄·͈༝·͈˄*₎◞ ̑̑

**Comment by Anticorianderist** [comment]
这句话结合上下文是这个意思：一般比较蠢的人喜欢强调“一眼把别人看穿”，但其实没有人可以被一眼看穿。所以，读人的水平高低需要一个普适的标准：你可以从对方的言行举止拿到多少有用信息，这是一个通用的说法。比如，读人水平非常高的人，仅仅半小时的对谈，他就可以摸清你什么能耐，对于他有什么用处；读人水平非常低的人，同样半小时的对谈，他得到的信息很少，甚至错得离谱。

关键词——有用信息：首先，你得有动机，进而才存在有用无用之说。以你所说的第二点为例，你根本不需要彻底地了解一个人，因为绝大部分人只是你人生的过客。比如白银杀人案的凶手。假如你的动机是离这种反社会人格越远越好，那么你只需要知道他是不是变态，不需要知道他喜欢什么颜色、喜欢什么食物等。但一个人精神是否病态，算是非常明显的信息之一了。变态之所以是变态，其细节非常丰富，只是各路牛鬼蛇神为了吸引眼球或怎样，将绝大部分人事物的原貌歪曲得“非眼见都是屁话”了。像我对这个问题的态度就是，我会远离正常人数量不及格的地方（穷山恶水出刁民）。对于感觉人格有点毛病的人，离得远一点而且照顾ta们的情绪，以防对方走极端。你这个例子非常不具有代表性，因为被那种人害命的概率可能比出车祸还小。

关键词——对方的言行举止：在这个读人的设定下，你是主体；对方是客体。还是以你的例子来说。假如我是一个女孩子，现在有一个渣男在我面前故作深情。要是我的水平很高，我从他那里拿到的信息就是“这个人光有嘴上功夫，不靠谱”；要是我的水平很低，我被他的话带着走。那只有一个可能，我不是被他的渣骗到，而是被他的颜值俘获了，心甘情愿地被骗。

不妨拿你的学习环境举例，假如对方是你的任课老师，你只需要知道对方的课程质量或给分情况，你（主体）就可以去主动地控制信息的摄入，比如只去第一节课和最后一节课，中间那些被你略过了。此外，同样地，你不需要知道你老师喜欢什么颜色、喜欢吃什么。

顶级的情商，永远不可能被对方带着走。如果对方（客体）反客为主，试图操纵什么，说明对方至少认为自己有能力PUA，而且试图PUA你，至少打算构造一些信息不对称获利。确实，读人的准确性与阅历有关。你年纪轻、阅历浅就可能被骗，但段位高的人确实不可能被PUA，比如谁要是试图PUA我，我可以玩死ta。如果你真的达到了原文合理化周围人事物的水平，你应该是在你周围的圈子里情商最高的人之一了。在那之前，把所有不合理的人事物先想清楚就行。奉行一个原则：“在清楚对方的动机之前，一个字都别信。”这就立于不败之地了。

**Comment by Anticorianderist** [comment]
> 这句话结合上下文是这个意思：一般比较蠢的人喜欢强调“一眼把别人看穿”，但其实没有人可以被一眼看穿。所以，读人的水平高低需要一个普适的标准：你可以从对方的言行举止拿到多少有用信息，这是一个通用的说法。比如，读人水平非常高的人，仅仅半小时的对谈，他就可以摸清你什么能耐，对于他有什么用处；读人水平非常低的人，同样半小时的对谈，他得到的信息很少，甚至错得离谱。
> 
> 关键词——有用信息：首先，你得有动机，进而才存在有用无用之说。以你所说的第二点为例，你根本不需要彻底地了解一个人，因为绝大部分人只是你人生的过客。比如白银杀人案的凶手。假如你的动机是离这种反社会人格越远越好，那么你只需要知道他是不是变态，不需要知道他喜欢什么颜色、喜欢什么食物等。但一个人精神是否病态，算是非常明显的信息之一了。变态之所以是变态，其细节非常丰富，只是各路牛鬼蛇神为了吸引眼球或怎样，将绝大部分人事物的原貌歪曲得“非眼见都是屁话”了。像我对这个问题的态度就是，我会远离正常人数量不及格的地方（穷山恶水出刁民）。对于感觉人格有点毛病的人，离得远一点而且照顾ta们的情绪，以防对方走极端。你这个例子非常不具有代表性，因为被那种人害命的概率可能比出车祸还小。
> 
> 关键词——对方的言行举止：在这个读人的设定下，你是主体；对方是客体。还是以你的例子来说。假如我是一个女孩子，现在有一个渣男在我面前故作深情。要是我的水平很高，我从他那里拿到的信息就是“这个人光有嘴上功夫，不靠谱”；要是我的水平很低，我被他的话带着走。那只有一个可能，我不是被他的渣骗到，而是被他的颜值俘获了，心甘情愿地被骗。
> 
> 不妨拿你的学习环境举例，假如对方是你的任课老师，你只需要知道对方的课程质量或给分情况，你（主体）就可以去主动地控制信息的摄入，比如只去第一节课和最后一节课，中间那些被你略过了。此外，同样地，你不需要知道你老师喜欢什么颜色、喜欢吃什么。
> 
> 顶级的情商，永远不可能被对方带着走。如果对方（客体）反客为主，试图操纵什么，说明对方至少认为自己有能力PUA，而且试图PUA你，至少打算构造一些信息不对称获利。确实，读人的准确性与阅历有关。你年纪轻、阅历浅就可能被骗，但段位高的人确实不可能被PUA，比如谁要是试图PUA我，我可以玩死ta。如果你真的达到了原文合理化周围人事物的水平，你应该是在你周围的圈子里情商最高的人之一了。在那之前，把所有不合理的人事物先想清楚就行。奉行一个原则：“在清楚对方的动机之前，一个字都别信。”这就立于不败之地了。

这句话结合上下文是这个意思：一般比较蠢的人喜欢强调“一眼把别人看穿”，但其实没有人可以被一眼看穿。所以，读人的水平高低需要一个普适的标准：你可以从对方的言行举止拿到多少有用信息，这是一个通用的说法。比如，读人水平非常高的人，仅仅半小时的对谈，他就可以摸清你什么能耐，对于他有什么用处；读人水平非常低的人，同样半小时的对谈，他得到的信息很少，甚至错得离谱。

关键词——有用信息：首先，你得有动机，进而才存在有用无用之说。以你所说的第二点为例，你根本不需要彻底地了解一个人，因为绝大部分人只是你人生的过客。比如白银杀人案的凶手。假如你的动机是离这种反社会人格越远越好，那么你只需要知道他是不是变态，不需要知道他喜欢什么颜色、喜欢什么食物等。但一个人精神是否病态，算是非常明显的信息之一了。变态之所以是变态，其细节非常丰富，只是各路牛鬼蛇神为了吸引眼球或怎样，将绝大部分人事物的原貌歪曲得“非眼见都是屁话”了。像我对这个问题的态度就是，我会远离正常人数量不及格的地方（穷山恶水出刁民）。对于感觉人格有点毛病的人，离得远一点而且照顾ta们的情绪，以防对方走极端。你这个例子非常不具有代表性，因为被那种人害命的概率可能比出车祸还小。

关键词——对方的言行举止：在这个读人的设定下，你是主体；对方是客体。还是以你的例子来说。假如我是一个女孩子，现在有一个渣男在我面前故作深情。要是我的水平很高，我从他那里拿到的信息就是“这个人光有嘴上功夫，不靠谱”；要是我的水平很低，我被他的话带着走。那只有一个可能，我不是被他的渣骗到，而是被他的颜值俘获了，心甘情愿地被骗。

不妨拿你的学习环境举例，假如对方是你的任课老师，你只需要知道对方的课程质量或给分情况，你（主体）就可以去主动地控制信息的摄入，比如只去第一节课和最后一节课，中间那些被你略过了。此外，同样地，你不需要知道你老师喜欢什么颜色、喜欢吃什么。

顶级的情商，永远不可能被对方带着走。如果对方（客体）反客为主，试图操纵什么，说明对方至少认为自己有能力PUA，而且试图PUA你，至少打算构造一些信息不对称获利。确实，读人的准确性与阅历有关。你年纪轻、阅历浅就可能被骗，但段位高的人确实不可能被PUA，比如谁要是试图PUA我，我可以玩死ta。如果你真的达到了原文合理化周围人事物的水平，你应该是在你周围的圈子里情商最高的人之一了。在那之前，把所有不合理的人事物先想清楚就行。奉行一个原则：“在清楚对方的动机之前，一个字都别信。”这就立于不败之地了。

**Comment by Anticorianderist** [comment]
> 

这句话结合上下文是这个意思：一般比较蠢的人喜欢强调“一眼把别人看穿”，但其实没有人可以被一眼看穿。所以，读人的水平高低需要一个普适的标准：你可以从对方的言行举止拿到多少有用信息，这是一个通用的说法。比如，读人水平非常高的人，仅仅半小时的对谈，他就可以摸清你什么能耐，对于他有什么用处；读人水平非常低的人，同样半小时的对谈，他得到的信息很少，甚至错得离谱。

关键词——有用信息：首先，你得有动机，进而才存在有用无用之说。以你所说的第二点为例，你根本不需要彻底地了解一个人，因为绝大部分人只是你人生的过客。比如白银杀人案的凶手。假如你的动机是离这种反社会人格越远越好，那么你只需要知道他是不是变态，不需要知道他喜欢什么颜色、喜欢什么食物等。但一个人精神是否病态，算是非常明显的信息之一了。变态之所以是变态，其细节非常丰富，只是各路牛鬼蛇神为了吸引眼球或怎样，将绝大部分人事物的原貌歪曲得“非眼见都是屁话”了。像我对这个问题的态度就是，我会远离正常人数量不及格的地方（穷山恶水出刁民）。对于感觉人格有点毛病的人，离得远一点而且照顾ta们的情绪，以防对方走极端。你这个例子非常不具有代表性，因为被那种人害命的概率可能比出车祸还小。

关键词——对方的言行举止：在这个读人的设定下，你是主体；对方是客体。还是以你的例子来说。假如我是一个女孩子，现在有一个渣男在我面前故作深情。要是我的水平很高，我从他那里拿到的信息就是“这个人光有嘴上功夫，不靠谱”；要是我的水平很低，我被他的话带着走。那只有一个可能，我不是被他的渣骗到，而是被他的颜值俘获了，心甘情愿地被骗。

不妨拿你的学习环境举例，假如对方是你的任课老师，你只需要知道对方的课程质量或给分情况，你（主体）就可以去主动地控制信息的摄入，比如只去第一节课和最后一节课，中间那些被你略过了。此外，同样地，你不需要知道你老师喜欢什么颜色、喜欢吃什么。

顶级的情商，永远不可能被对方带着走。如果对方（客体）反客为主，试图操纵什么，说明对方至少认为自己有能力PUA，而且试图PUA你，至少打算构造一些信息不对称获利。确实，读人的准确性与阅历有关。你年纪轻、阅历浅就可能被骗，但段位高的人确实不可能被PUA，比如谁要是试图PUA我，我可以玩死ta。如果你真的达到了原文合理化周围人事物的水平，你应该是在你周围的圈子里情商最高的人之一了。在那之前，把所有不合理的人事物先想清楚就行。奉行一个原则：“在清楚对方的动机之前，一个字都别信。”这就立于不败之地了。

**Comment by Anticorianderist** [comment]
> 更合理的读人标准，应该是对方的言行举止向你透露了多少有用信息。
> 
> ps:请教一下学长，这个意思是具体什么意思？
> 
> 如果说从你观察到的对方的言行去判断这个人，还要观察是否对方透露。
> 
> 1. 存在一个人特地向你透露片面的信息。比如渣男对女性的片面信息去，读人不就有偏差了。
>    2.人是多面的 你不能从一个人向你透露的言行彻底了解一个人。可能对普通人还能说的通。对我影响最深的就是白银杀人案的凶手了。
> 
> 是否说说高手可以见微知著呢？
> 
> 顺便感谢之前学长的答复₍˄·͈༝·͈˄*₎◞ ̑̑

这句话结合上下文是这个意思：一般比较蠢的人喜欢强调“一眼把别人看穿”，但其实没有人可以被一眼看穿。所以，读人的水平高低需要一个普适的标准：你可以从对方的言行举止拿到多少有用信息，这是一个通用的说法。比如，读人水平非常高的人，仅仅半小时的对谈，他就可以摸清你什么能耐，对于他有什么用处；读人水平非常低的人，同样半小时的对谈，他得到的信息很少，甚至错得离谱。

关键词——有用信息：首先，你得有动机，进而才存在有用无用之说。以你所说的第二点为例，你根本不需要彻底地了解一个人，因为绝大部分人只是你人生的过客。比如白银杀人案的凶手。假如你的动机是离这种反社会人格越远越好，那么你只需要知道他是不是变态，不需要知道他喜欢什么颜色、喜欢什么食物等。但一个人精神是否病态，算是非常明显的信息之一了。变态之所以是变态，其细节非常丰富，只是各路牛鬼蛇神为了吸引眼球或怎样，将绝大部分人事物的原貌歪曲得“非眼见都是屁话”了。像我对这个问题的态度就是，我会远离正常人数量不及格的地方（穷山恶水出刁民）。对于感觉人格有点毛病的人，离得远一点而且照顾ta们的情绪，以防对方走极端。你这个例子非常不具有代表性，因为被那种人害命的概率可能比出车祸还小。

关键词——对方的言行举止：在这个读人的设定下，你是主体；对方是客体。还是以你的例子来说。假如我是一个女孩子，现在有一个渣男在我面前故作深情。要是我的水平很高，我从他那里拿到的信息就是“这个人光有嘴上功夫，不靠谱”；要是我的水平很低，我被他的话带着走。那只有一个可能，我不是被他的渣骗到，而是被他的颜值俘获了，心甘情愿地被骗。

不妨拿你的学习环境举例，假如对方是你的任课老师，你只需要知道对方的课程质量或给分情况，你（主体）就可以去主动地控制信息的摄入，比如只去第一节课和最后一节课，中间那些被你略过了。此外，同样地，你不需要知道你老师喜欢什么颜色、喜欢吃什么。

顶级的情商，永远不可能被对方带着走。如果对方（客体）反客为主，试图操纵什么，说明对方至少认为自己有能力PUA，而且试图PUA你，至少打算构造一些信息不对称获利。确实，读人的准确性与阅历有关。你年纪轻、阅历浅就可能被骗，但段位高的人确实不可能被PUA，比如谁要是试图PUA我，我可以玩死ta。如果你真的达到了原文合理化周围人事物的水平，你应该是在你周围的圈子里情商最高的人之一了。在那之前，把所有不合理的人事物先想清楚就行。奉行一个原则：“在清楚对方的动机之前，一个字都别信。”这就立于不败之地了。
