### ISSUE TITLE
关于混沌论的疑问

### ISSUE THREAD

**Issue by Alizestl** [Anticorianderist/de-vegetable#5]
读您的文字让我受益匪浅，对此致以诚挚的谢意。

在读混沌论这一段时，我对以下三句话有一些疑惑，恳请求解。
“混沌论告诉我们，守好分内寸土即可。”
”如果知道自己能力的边界在哪（“见自己”的必要条件），则边界之外的世界均为混沌。“
“一言以蔽之，混沌论放弃未来。”

Q1：
在高中时期，我形成了一种思维模式，将世界分为人身小天地与外界大天地。
自己能够掌控的变量归于前者范畴，其余不可控的变量都归于后者范畴。
请问我的这种思维模式，在您看来，是否属于混沌论的一种变式，是否有优化重构的更佳路径？

Q2：
知晓自己能力边界后，我们可以去主动对抗外界的混沌并获胜，以此来拓展自己的边界吗？
当然这里的对抗并不是指您前文写的“与喷子唇枪舌战”等，
而是自发地去假想、模拟自己未经历过的困境，比如社会关系中如何对抗突然的道德绑架等。
（由于我不太擅长这种事情，并且有点被害妄想症，所以总会在无聊时去设想这类场景，为以后碰到这种情况做准备。）

Q3：
“一言以蔽之，混沌论放弃未来。”
这句话的意思是，不要去思考那些虚无缥缈、难以预测的未来之事，先做好对过去的描述，再考虑对未来的论述吗？
本人愚笨，思考许久，依然自觉读不懂这句话。望您答疑解惑。

**Comment by sakura241225** [comment]
我试着说明一下。
是不是类似于舒适区还有学习区和危险区。
如果你

**Comment by sakura241225** [comment]
> 读您的文字让我受益匪浅，对此致以诚挚的谢意。
> 
> 在读混沌论这一段时，我对以下三句话有一些疑惑，恳请求解。
> “混沌论告诉我们，守好分内寸土即可。”
> ”如果知道自己能力的边界在哪（“见自己”的必要条件），则边界之外的世界均为混沌。“
> “一言以蔽之，混沌论放弃未来。”
> 
> Q1：
> 在高中时期，我形成了一种思维模式，将世界分为人身小天地与外界大天地。
> 自己能够掌控的变量归于前者范畴，其余不可控的变量都归于后者范畴。
> 请问我的这种思维模式，在您看来，是否属于混沌论的一种变式，是否有优化重构的更佳路径？
> 
> Q2：
> 知晓自己能力边界后，我们可以去主动对抗外界的混沌并获胜，以此来拓展自己的边界吗？
> 当然这里的对抗并不是指您前文写的“与喷子唇枪舌战”等，
> 而是自发地去假想、模拟自己未经历过的困境，比如社会关系中如何对抗突然的道德绑架等。
> （由于我不太擅长这种事情，并且有点被害妄想症，所以总会在无聊时去设想这类场景，为以后碰到这种情况做准备。）
> 
> Q3：
> “一言以蔽之，混沌论放弃未来。”
> 这句话的意思是，不要去思考那些虚无缥缈、难以预测的未来之事，先做好对过去的描述，再考虑对未来的论述吗？
> 本人愚笨，思考许久，依然自觉读不懂这句话。望您答疑解惑。
> 
> 

我试着说明一下。不知理解的是否正确。
顺便🐷学长生日快乐！

混沌论分为有规律的（危险区）和暂时不知有规律的事物（虚无）。

对于有规律的混沌事物，由缓自至急，训训渐进，根据i+1法则，慢慢学习自己能做到的事情。然后对于混沌事物进行忽略。

1.危险区: 是一种表示对自己很难知识  舒适区还有学习区和危险区学习能力化分。
如果目标过高，自己能力达不到理解和学习的地步，会花费大量时间而无意义。比如小学生学高数（天才除外）

2.混沌论: 毫无规律的东西。不是对其所处的时间够不够或者自己聪明与否，而是有一直限制，例如地址的预测，例如一个人对彩票的概率进行研究，花费大量时间而无意义，或者要制造永动机。
一旦选择没有规律的目标，而非得研究一个规律。

无论如何，不能超过自己理解能力。

**Comment by Anticorianderist** [comment]
问得非常清晰。顺便谢谢sakura241225的评论以及生日祝福！

其实你们这一问一答就很好地说明了问题的根源：**我们思维模式的底座不一样。**我先简短地一一回复3个问题，然后对原文稍作补充。

A1：在我看来，你的思维模式是决定论、概率论与混沌论的一种变式（而不仅仅是混沌论的变式），而其优化重构的关键在乎加入一种**不重不漏的分割**。原文没有以**集合**的视角强调：正定、欠定、超定三个集合加起来覆盖了所有的情况（**不漏**），而且正定、欠定、超定两两之间毫无交集（**不重**）；进而，正定对应的决定论、欠定对应的概率论、超定对应的混沌论也是一种在**现实意义**上不重不漏的分割；再进而，决定论对应的过去、概率论对应的现在、混沌论对应的未来也是一种在**人生**上不重不漏的分割。

你的思维模式没有概率论这种“可控，但不是完全可控”的情况，以致于在**决策**的时候不够完美。这是数学篇的第5篇文章（下一篇文章）的写作重点。

A2：从本质上看，这个问题其实是一种**从不可控到可控的转化**。在你看来，我们已经得到了现有的人身小天地，可以通过一些人为的努力去把外界大天地（混沌）纳入自己的能力边界之内；在sakura241225看来，ta用了一些我写在本书之外的词汇（危险区、舒适区、学习区、i + 1法则等）描述从不可控到可控转化的**方法论**与**注意事项**；为了解释我的思维模式的底座，我通过一个具体的例子，写写原文这套模型是怎么转化的。

假如现在是2000-01-01，我将参加2000-06-07和2000-06-08的高考。为了简单起见，我们只说数学。

**决定论解释过去**：我看到了1995-1999的高考数学真题。12道选择题、4道填空题、6道解答题。解答题分为：数列或三角函数、立体几何、概率、圆锥曲线、导数、平面几何或极坐标或不等式三选一。1995-1999的难度分别是：难、易、中、中、易。怎么解释过去呢？1995的数学很难，平均分太低了；1996简单一点；1996简单过头了，1997调难一点；1998趋于稳态；1999换了命题组组长，ta怕别人骂ta，于是第1次命题下手比较轻，简单一点。

也就是说，**关于过去，你可以极尽调研之能事，让发生的每个细节都很合理。**对于这场高考、你的社交关系、你经历的所有事情，只要你的视角足够广，而且相关的人事物足够重要（存在合理化的价值和意义），你可以运用“见自己”的能力，把过去的一切都合理化。

**概率论决定现在**：既然1995-1999的难度是：难、易、中、中、易，那么我猜2000即将参加的那场数学考试，难度的可能性：难 > 中 > 易。这个指导是有意义的。既然那张试卷可能很难，那么我就应该多做难题，少刷简单题。

也就是说，**关于现在，其实只有一些估计，但这个估计基于对过去合理化的程度。**比如，我合理化了1995-1999的高考数学真题的难度，我可以得到的、关于未来那张试卷的信息是“难的可能性最大、其次是中、然后是易”；要是更进一步，从每个题型的细节入手，发现数列或三角函数那道题各自隔年出一次，而且去年的不等式比极坐标难很多很多，我可以进一步得到的、关于那张试卷的信息是“难的可能性最大，其次是中、然后是易；今年极有可能考三角函数，因为去年考了数列；不等式会比较简单”。这对于我的备考策略的影响程度是不同的。

**混沌论放弃未来**：1999命题组组长因为泄题被抓，换人了（对难度的估计直接报废）；2000高考数学开考前夜刮台风，试卷毁了，被迫启用备用卷（对考试内容的估计直接报废）。

总结一下就是，通过**决定论**所合理化的**过去**（往年真题），**决定**正在备考的**现在**（备考的倾向性，进而对抗所谓的未来），放弃思考那些完完全全把握不住的事情所影响的**未来**。

所以，你看，我们三个写的东西完全不一样。至于你所说的拓展边界（从非可控到可控的转化），随着时间的流逝，在备考过程中，我**现在**所经历的每分每秒都将成为**过去**。继续举例，假如我今天做了一道数列大题，不会。把它学会（合理化）就是一个**现在（概率论）**成为**过去（决定论）**的过程。用你的原话（假想）来说，我们正是在假想那些存在一些规律，但不完全确定的可能性，并作出反应。

A3：有了A2的铺垫。A3就直接抛结论了。这句话（混沌论放弃未来）的意思是：做好对过去的描述（合理化）；根据对未来那些可能性的假想，做好现在的事情；等待未来难以捉摸的天意。

数学篇的意义在于使用数学思想，从而得到真正的因果。原文确实没有强调这种基于数学的思维方式的优越性，但如果用得好，你将成为一个非常有主见的人，而且对人事物的分析将有ta人所无法撼动的自信（不是无脑的自负）。这也再次回答了Q1。

**Comment by Alizestl** [comment]
> 问得非常清晰。顺便谢谢sakura241225的评论以及生日祝福！
> 
> 其实你们这一问一答就很好地说明了问题的根源：**我们思维模式的底座不一样。**我先简短地一一回复3个问题，然后对原文稍作补充。
> 
> A1：在我看来，你的思维模式是决定论、概率论与混沌论的一种变式（而不仅仅是混沌论的变式），而其优化重构的关键在乎加入一种**不重不漏的分割**。原文没有以**集合**的视角强调：正定、欠定、超定三个集合加起来覆盖了所有的情况（**不漏**），而且正定、欠定、超定两两之间毫无交集（**不重**）；进而，正定对应的决定论、欠定对应的概率论、超定对应的混沌论也是一种在**现实意义**上不重不漏的分割；再进而，决定论对应的过去、概率论对应的现在、混沌论对应的未来也是一种在**人生**上不重不漏的分割。
> 
> 你的思维模式没有概率论这种“可控，但不是完全可控”的情况，以致于在**决策**的时候不够完美。这是数学篇的第5篇文章（下一篇文章）的写作重点。
> 
> A2：从本质上看，这个问题其实是一种**从不可控到可控的转化**。在你看来，我们已经得到了现有的人身小天地，可以通过一些人为的努力去把外界大天地（混沌）纳入自己的能力边界之内；在sakura241225看来，ta用了一些我写在本书之外的词汇（危险区、舒适区、学习区、i + 1法则等）描述从不可控到可控转化的**方法论**与**注意事项**；为了解释我的思维模式的底座，我通过一个具体的例子，写写原文这套模型是怎么转化的。
> 
> 假如现在是2000-01-01，我将参加2000-06-07和2000-06-08的高考。为了简单起见，我们只说数学。
> 
> **决定论解释过去**：我看到了1995-1999的高考数学真题。12道选择题、4道填空题、6道解答题。解答题分为：数列或三角函数、立体几何、概率、圆锥曲线、导数、平面几何或极坐标或不等式三选一。1995-1999的难度分别是：难、易、中、中、易。怎么解释过去呢？1995的数学很难，平均分太低了；1996简单一点；1996简单过头了，1997调难一点；1998趋于稳态；1999换了命题组组长，ta怕别人骂ta，于是第1次命题下手比较轻，简单一点。
> 
> 也就是说，**关于过去，你可以极尽调研之能事，让发生的每个细节都很合理。**对于这场高考、你的社交关系、你经历的所有事情，只要你的视角足够广，而且相关的人事物足够重要（存在合理化的价值和意义），你可以运用“见自己”的能力，把过去的一切都合理化。
> 
> **概率论决定现在**：既然1995-1999的难度是：难、易、中、中、易，那么我猜2000即将参加的那场数学考试，难度的可能性：难 > 中 > 易。这个指导是有意义的。既然那张试卷可能很难，那么我就应该多做难题，少刷简单题。
> 
> 也就是说，**关于现在，其实只有一些估计，但这个估计基于对过去合理化的程度。**比如，我合理化了1995-1999的高考数学真题的难度，我可以得到的、关于未来那张试卷的信息是“难的可能性最大、其次是中、然后是易”；要是更进一步，从每个题型的细节入手，发现数列或三角函数那道题各自隔年出一次，而且去年的不等式比极坐标难很多很多，我可以进一步得到的、关于那张试卷的信息是“难的可能性最大，其次是中、然后是易；今年极有可能考三角函数，因为去年考了数列；不等式会比较简单”。这对于我的备考策略的影响程度是不同的。
> 
> **混沌论放弃未来**：1999命题组组长因为泄题被抓，换人了（对难度的估计直接报废）；2000高考数学开考前夜刮台风，试卷毁了，被迫启用备用卷（对考试内容的估计直接报废）。
> 
> 总结一下就是，通过**决定论**所合理化的**过去**（往年真题），**决定**正在备考的**现在**（备考的倾向性，进而对抗所谓的未来），放弃思考那些完完全全把握不住的事情所影响的**未来**。
> 
> 所以，你看，我们三个写的东西完全不一样。至于你所说的拓展边界（从非可控到可控的转化），随着时间的流逝，在备考过程中，我**现在**所经历的每分每秒都将成为**过去**。继续举例，假如我今天做了一道数列大题，不会。把它学会（合理化）就是一个现在（**概率论**）成为过去（**决定论**）的过程。用你的原话（假想）来说，我们正是在假想那些存在一些规律，但不完全确定的可能性，并作出反应。
> 
> A3：有了A2的铺垫。A3就直接抛结论了。这句话（混沌论放弃未来）的意思是：**做好对过去的描述（合理化）；根据对未来那些可能性的假想，做好现在的事情；等待未来难以捉摸的天意。**
> 
> 数学篇的意义在于使用数学思想，从而得到真正的因果。原文确实没有强调这种基于数学的思维方式的优越性，但如果用得好，你将成为一个非常有主见的人，而且对人事物的分析将有ta人所无法撼动的自信（不是无脑的自负）。这也再次回答了Q1。

谢谢您宝贵的时间。生日快乐！
