### ISSUE TITLE
见众生的读人无偏

### ISSUE THREAD

**Issue by 0ojj** [Anticorianderist/de-vegetable#9]
如果因为周围环境中的某人的属性过于劣根例如黄赌毒而不与其交往并嗤之以鼻，是否算读"偏"了？但大部分人都会有一定劣根性，只是方向和程度上的不同，有些人一些方面劣根但其他方面是好的，甚至罪可至死罪大恶极的白银碎石案凶手在平日里是个大孝子、和善的人，据此如何做到读人的"无偏"呢？

**Comment by 0ojj** [comment]
> > 如果因为周围环境中的某人的属性过于劣根例如黄赌毒而不与其交往并嗤之以鼻，是否算读"偏"了？但大部分人都会有一定劣根性，只是方向和程度上的不同，有些人一些方面劣根但其他方面是好的，甚至罪可至死罪大恶极的白银碎石案凶手在平日里是个大孝子、和善的人，据此如何做到读人的"无偏"呢？
> 
> 
> 
> 所谓的“无偏”，即把你换成一个与ta利益无关的人，还是可以得到相同的结论。
> 
> 
> 
> 如果你因为某些人的某些特质讨厌ta，这当然不算读“偏”了。因为人有偏好，所以人有爱憎。但是，对ta的态度和读ta完全是两码事。
> 
> 
> 
> 比如白银案的凶手。你知道他罪大恶极，但他平时是一个大孝子。这其实是无偏的评价，因为你是外人。假如把他扔到你的社交圈，你自然会对他敬而远之。所以，读人读的是结论。
> 
> 
> 
> 无偏：某人黄赌毒，所以我不和ta一起玩。
> 
> 有偏：某人黄赌毒，那么这个人一定没孝心吧？
> 
> 
> 
> 其实偏不偏的本质，在于你会不会将你对ta的情绪蔓延到事实之外。你可以把无偏理解为就事论事，对事不对人。
> 
> 
> 
> PS：为什么你们都喜欢用白银案作为例子？

可能因为这个例子大家都知道吧🫠
如果身边人亲近的人有一些劣根性，例如赌博的父母，校园bl、pc的同学等等。交往时，他们真心地对你好。和他们正常相处接触不到他们的阴暗面能够融洽交往，但交往到一定深度时，触碰到他们的阴暗面并尝试用真善美一定程度上净化他们，他们却承认自己的劣根并认为没有被净化而是刺痛。我不知是否有交往下去的必要。我不知是否该尝试改变他们。是没有改变的方法还是没有改变的必要😵‍💫，有时我能感到他们因我而变得好了一些，可好像本质还是没有变。见众生该只停留在“见”和“读”上吗😭。

**Comment by sakura241225** [comment]
> 不要对他人抱以期待。不要好自为师。过好自己。

**Comment by sakura241225** [comment]
不要好自为师。
首先，判断自己不好自为师的前提是把自己过好。
其次，他人的问题。分为很多中情况。即使有一个人打算自杀，如果他下定决心，你能做的所有都是无用功。eg海贼王中路飞让罗宾大喊自己要活下去。然后才行动。为什么？ 因为必须自己有改变的想法才能印象他人。内因决定外因。你做的很多不过对他人来说是外因。
最后，即使做好自己了。也不要轻易否定他人生活。可以看不起。别花费时间改变。有时候他们的生活是必然的，决定与他们所见的世界，他们的生活经历。eg。比如你到了印度，批评，希望他人尊重妇女。

ps：充满爱是好的。我很肯定你的想法。

**Comment by 0ojj** [comment]
很宝贵的建议！感谢回复☺️，思绪变得清晰和明朗。

**Comment by sakura241225** [comment]
对于他人的缺点保持的原则明确。比如你要求自己的配偶肯定和一些不经常打交道的陌生人是不一样的。如果你接受朋友pc，你能接受妻子或丈夫出轨吗？情况不同。如果你朋友校园霸凌，或者你朋友你发现一直欺骗你，你可能就不认为他是朋友。
还有一种情况。就是一个人发生一些事情变得极端，这是特殊情况。

  今天下午和自己的父母吵，我一怒之下把自己的手机摔了。然后又开始问自己为何父母这样子？ 他们明明问题那么明显，为什么不去改呢？为什么这样对我？回过头来，想了想，他们可能是根本不明白好坏，他们认为这样做就是好的，你是改变不了的。你只能改变你自己。我错误在于以前也这种情况没有更好的面对，而不是我没有改变他们。有时候他们认为是坏的，他们认为也无关紧要。
  我不清楚你是否和我一样是这种情况。如果是的话，你完全没有必要去想着去改变父母或者他人，你是改变不了的。

**Comment by Anticorianderist** [comment]
> > > 如果因为周围环境中的某人的属性过于劣根例如黄赌毒而不与其交往并嗤之以鼻，是否算读"偏"了？但大部分人都会有一定劣根性，只是方向和程度上的不同，有些人一些方面劣根但其他方面是好的，甚至罪可至死罪大恶极的白银碎石案凶手在平日里是个大孝子、和善的人，据此如何做到读人的"无偏"呢？
> > 
> > 
> > 所谓的“无偏”，即把你换成一个与ta利益无关的人，还是可以得到相同的结论。
> > 如果你因为某些人的某些特质讨厌ta，这当然不算读“偏”了。因为人有偏好，所以人有爱憎。但是，对ta的态度和读ta完全是两码事。
> > 比如白银案的凶手。你知道他罪大恶极，但他平时是一个大孝子。这其实是无偏的评价，因为你是外人。假如把他扔到你的社交圈，你自然会对他敬而远之。所以，读人读的是结论。
> > 无偏：某人黄赌毒，所以我不和ta一起玩。
> > 有偏：某人黄赌毒，那么这个人一定没孝心吧？
> > 其实偏不偏的本质，在于你会不会将你对ta的情绪蔓延到事实之外。你可以把无偏理解为就事论事，对事不对人。
> > PS：为什么你们都喜欢用白银案作为例子？
> 
> 可能因为这个例子大家都知道吧🫠 如果身边人亲近的人有一些劣根性，例如赌博的父母，校园bl、pc的同学等等。交往时，他们真心地对你好。和他们正常相处接触不到他们的阴暗面能够融洽交往，但交往到一定深度时，触碰到他们的阴暗面并尝试用真善美一定程度上净化他们，他们却承认自己的劣根并认为没有被净化而是刺痛。我不知是否有交往下去的必要。我不知是否该尝试改变他们。是没有改变的方法还是没有改变的必要😵‍💫，有时我能感到他们因我而变得好了一些，可好像本质还是没有变。见众生该只停留在“见”和“读”上吗😭。

我回答一下最后一句。当然不是。

因为你现在稳定地处在某个人生阶段，所以你感受不到见众生对于你自己潜移默化的影响。随着你不断地进入新的环境，这些“见”和“读”会影响你自己选择成为哪样的人，进入何种新圈子。当你和一些人渐行渐远，你自然而然地发现“见众生”和很多重要的人生节点相呼应。
